# Generated by Django 5.1.2 on 2025-04-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
    ]
